export const salesSummaryData = [
  {
    id: 1,
    period: "01 Jan - 07 Jan 2025",
    store: "Electro Mart",
    salesperson: "Carl Evans",
    totalSales: "$23,500",
    totalPaid: "$19,800",
    totalDue: "$3,700",
    totalOrders: "45",
    customerCount: "23",
    productCount: "70",
  },
  {
    id: 2,
    period: "08 Jan - 14 Jan 2025",
    store: "Quantum Gadgets",
    salesperson: "Minerva Rameriz",
    totalSales: "$18,200",
    totalPaid: "$16,000",
    totalDue: "$2,200",
    totalOrders: "36",
    customerCount: "18",
    productCount: "53",
  },
  {
    id: 3,
    period: "15 Jan - 21 Jan 2025",
    store: "Prime Bazaar",
    salesperson: "Robert Lamon",
    totalSales: "$29,900",
    totalPaid: "$25,100",
    totalDue: "$4,800",
    totalOrders: "52",
    customerCount: "31",
    productCount: "84",
  },
];

export const invoiceDetailData = [
  {
    id: 1,
    invoiceNo: "INV-1001",
    customer: "Carl Evans",
    date: "10 Jan 2025",
    store: "Electro Mart",
    amount: "$1,200",
    tax: "$120",
    discount: "$50",
    amountDue: "$330",
    status: "Partial",
  },
  {
    id: 2,
    invoiceNo: "INV-1002",
    customer: "Minerva Rameriz",
    date: "12 Jan 2025",
    store: "Quantum Gadgets",
    amount: "$2,800",
    tax: "$280",
    discount: "$120",
    amountDue: "$0",
    status: "Paid",
  },
  {
    id: 3,
    invoiceNo: "INV-1003",
    customer: "Robert Lamon",
    date: "15 Jan 2025",
    store: "Prime Bazaar",
    amount: "$3,100",
    tax: "$310",
    discount: "$70",
    amountDue: "$450",
    status: "Unpaid",
  },
];

export const productWiseSalesData = [
  {
    id: 1,
    productName: "Lenovo 3rd Generation",
    sku: "PT001",
    category: "Computers",
    warehouse: "Electro Mart",
    soldQty: "20",
    soldAmount: "$14,000",
    instockQty: "100",
  },
  {
    id: 2,
    productName: "Iphone 14 Pro",
    sku: "PT008",
    category: "Phone",
    warehouse: "Volt Vault",
    soldQty: "35",
    soldAmount: "$80,500",
    instockQty: "370",
  },
  {
    id: 3,
    productName: "Amazon Echo Dot",
    sku: "PT005",
    category: "Accessories",
    warehouse: "Quantum Gadgets",
    soldQty: "10",
    soldAmount: "$5,000",
    instockQty: "80",
  },
];

export const customerWiseSalesData = [
  {
    id: 1,
    customer: "Carl Evans",
    totalOrders: "18",
    totalAmount: "$15,200",
    paid: "$12,800",
    due: "$2,400",
    lastOrderDate: "14 Jan 2025",
    salesperson: "Carl Evans",
  },
  {
    id: 2,
    customer: "Minerva Rameriz",
    totalOrders: "12",
    totalAmount: "$11,600",
    paid: "$11,600",
    due: "$0",
    lastOrderDate: "13 Jan 2025",
    salesperson: "Minerva Rameriz",
  },
  {
    id: 3,
    customer: "Robert Lamon",
    totalOrders: "22",
    totalAmount: "$18,900",
    paid: "$16,100",
    due: "$2,800",
    lastOrderDate: "15 Jan 2025",
    salesperson: "Robert Lamon",
  },
];

export const salesReturnData = [
  {
    id: 1,
    returnNo: "RTN-2001",
    invoiceNo: "INV-1001",
    customer: "Carl Evans",
    date: "16 Jan 2025",
    total: "$320",
    paid: "$320",
    due: "$0",
    reason: "Defective item",
    status: "Completed",
  },
  {
    id: 2,
    returnNo: "RTN-2002",
    invoiceNo: "INV-1002",
    customer: "Minerva Rameriz",
    date: "18 Jan 2025",
    total: "$150",
    paid: "$0",
    due: "$150",
    reason: "Wrong color",
    status: "Pending",
  },
];

export const outstandingBalanceData = [
  {
    id: 1,
    customer: "Carl Evans",
    totalOrders: "18",
    outstandingBalance: "$2,400",
    lastPaymentDate: "14 Jan 2025",
    dueDays: "12",
  },
  {
    id: 2,
    customer: "Robert Lamon",
    totalOrders: "22",
    outstandingBalance: "$2,800",
    lastPaymentDate: "15 Jan 2025",
    dueDays: "8",
  },
  {
    id: 3,
    customer: "Patricia Lewis",
    totalOrders: "5",
    outstandingBalance: "$620",
    lastPaymentDate: "10 Jan 2025",
    dueDays: "20",
  },
];

export const gstSalesData = [
  {
    id: 1,
    invoiceNo: "INV-1001",
    customer: "Carl Evans",
    date: "10 Jan 2025",
    taxRate: "18%",
    taxableAmount: "$1,000",
    taxAmount: "$180",
    totalAmount: "$1,200",
    gstState: "CGST/SGST",
  },
  {
    id: 2,
    invoiceNo: "INV-1002",
    customer: "Minerva Rameriz",
    date: "12 Jan 2025",
    taxRate: "12%",
    taxableAmount: "$2,500",
    taxAmount: "$300",
    totalAmount: "$2,800",
    gstState: "CGST/SGST",
  },
  {
    id: 3,
    invoiceNo: "INV-1003",
    customer: "Robert Lamon",
    date: "15 Jan 2025",
    taxRate: "18%",
    taxableAmount: "$2,800",
    taxAmount: "$504",
    totalAmount: "$3,100",
    gstState: "CGST/SGST",
  },
];
